language: go
sudo: false

env:
  global:
    - GO111MODULE=on

matrix:
  include:
    - go: "1.12"
    - go: "1.13"

install:
  - go mod download

script:
  - go test

after_success:
  - make cover
  - bash <(curl -s https://codecov.io/bash)